src/BITS/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BITS.Models
{
    public class Customer
    {
        public int ID { get; set; }

        /// <summary>
        /// High-level id. Not for the database, but what is used in 3rd party systems
        /// </summary>
        public string IDNumber { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }

        [Display(Name = "Address 1")]
        [StringLength(100)]
        public string Address_0 { get; set; }

        [Display(Name = "Address 2")]
        [StringLength(100)]
        public string Address_1 { get; set; }

        [Display(Name = "Address 3")]
        [StringLength(100)]
        public string Address_2 { get; set; }

        [StringLength(100)]
        public string City { get; set; }

        [DataType(DataType.PostalCode)]
        public string Zip { get; set; }

        public int CountryID { get; set; }
        public Country Country { get; set; }

        [Display(Name = "Email address")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        public bool Enabled { get; set; } = true;

    }
}

src/BITS/Controllers/CustomerContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BITS.Data;
using BITS.Models;

namespace BITS.Controllers
{
    public class CustomerContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomerContactsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: CustomerContacts
        public async Task<IActionResult> Index(int? id)
        {
            var customerContacts = from cc in _context.CustomerContact
                                   select cc;

            customerContacts = customerContacts.Where(cc => cc.CustomerID == id).Include(c => c.Customer);

            ViewData["Customer"] = await _context.Customer.Where(c => c.ID == id).SingleAsync();

            return View(await customerContacts.ToListAsync());
        }

        // GET: CustomerContacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerContact = await _context.CustomerContact.SingleOrDefaultAsync(m => m.ID == id);
            if (customerContact == null)
            {
                return NotFound();
            }

            return View(customerContact);
        }

        // GET: CustomerContacts/Create
        public async Task<IActionResult> Create(int id)
        {
            //ViewData["CustomerID"] = HtmlHelperInputExtensions.Hidden()
            //new HiddenInputAttribute(_context.Customer, );
            //new SelectList(_context.Customer, "ID", "Name");
            ViewData["Customer"] = await _context.Customer.Where(c => c.ID == id).FirstAsync();
            return View();
        }

        // POST: CustomerContacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,EmailAddress_1,EmailAddress_2,Enabled,Name,PhoneNumber_1,PhoneNumber_2")] CustomerContact customerContact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customerContact);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = customerContact.CustomerID });
            }
            ViewData["CustomerID"] = customerContact.CustomerID;
            return View(customerContact);
        }

        // GET: CustomerContacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerContact = await _context.CustomerContact.SingleOrDefaultAsync(m => m.ID == id);
            if (customerContact == null)
            {
                return NotFound();
            }
            ViewData["CustomerID"] = new SelectList(_context.Customer, "ID", "Name", customerContact.CustomerID);

            ViewData["Customer"] = await _context.Customer.Where(c => c.ID == customerContact.CustomerID).SingleAsync();

            return View(customerContact);
        }

        // POST: CustomerContacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CustomerID,EmailAddress_1,EmailAddress_2,Enabled,Name,PhoneNumber_1,PhoneNumber_2")] CustomerContact customerContact)
        {
            if (id != customerContact.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customerContact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerContactExists(customerContact.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CustomerID"] = new SelectList(_context.Customer, "ID", "Name", customerContact.CustomerID);
            return View(customerContact);
        }

        // GET: CustomerContacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerContact = await _context.CustomerContact.SingleOrDefaultAsync(m => m.ID == id);
            if (customerContact == null)
            {
                return NotFound();
            }

            return View(customerContact);
        }

        // POST: CustomerContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customerContact = await _context.CustomerContact.SingleOrDefaultAsync(m => m.ID == id);
            _context.CustomerContact.Remove(customerContact);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CustomerContactExists(int id)
        {
            return _context.CustomerContact.Any(e => e.ID == id);
        }
    }
}

src/BITS/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BITS.Data;
using BITS.Models;

namespace BITS.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Customer.Include(c => c.Country);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "Name");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Address_0,Address_1,Address_2,City,CountryID,EmailAddress,Enabled,IDNumber,Name,Zip")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "Name", customer.CountryID);
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "Name", customer.CountryID);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Address_0,Address_1,Address_2,City,CountryID,EmailAddress,Enabled,IDNumber,Name,Zip")] Customer customer)
        {
            if (id != customer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "Name", customer.CountryID);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.ID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.ID == id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.ID == id);
        }
    }
}

src/BITS/Views/Customers/Create.cshtml
@model BITS.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Address_0" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_0" class="form-control" />
                <span asp-validation-for="Address_0" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address_1" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_1" class="form-control" />
                <span asp-validation-for="Address_1" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address_2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_2" class="form-control" />
                <span asp-validation-for="Address_2" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CountryID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CountryID" class ="form-control" asp-items="ViewBag.CountryID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="Enabled" />
                    <label asp-for="Enabled"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IDNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IDNumber" class="form-control" />
                <span asp-validation-for="IDNumber" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Zip" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/BITS/Views/Customers/Delete.cshtml
@model BITS.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address_0)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_0)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address_1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address_2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/BITS/Views/Customers/Details.cshtml
@model BITS.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address_0)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_0)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address_1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address_2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address_2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/BITS/Views/Customers/Edit.cshtml
@model BITS.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Address_0" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_0" class="form-control" />
                <span asp-validation-for="Address_0" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address_1" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_1" class="form-control" />
                <span asp-validation-for="Address_1" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address_2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address_2" class="form-control" />
                <span asp-validation-for="Address_2" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CountryID" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="CountryID" class="form-control" asp-items="ViewBag.CountryID"></select>
                <span asp-validation-for="CountryID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="Enabled" />
                    <label asp-for="Enabled"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IDNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IDNumber" class="form-control" />
                <span asp-validation-for="IDNumber" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Zip" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/BITS/Views/Customers/Index.cshtml
@model IEnumerable<BITS.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address_0)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address_1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address_2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enabled)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address_0)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address_1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address_2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enabled)
            </td>
            
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-controller="CustomerContacts" asp-action="Index" asp-route-id="@item.ID">Contacts</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>